name: "wolfi-act"
description: "Dynamic GitHub Actions from Wolfi packages"
inputs:
  packages:
    description: "Comma-separated list of Wolfi packages to install"
    required: true
  command:
    description: "Command to run"
    required: true
  apko-image:
    description: "The apko image to build with"
    required: true
    default: "ghcr.io/wolfi-dev/apko:latest"
  debug:
    description: "Whether or not to add debug logging"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -e

        debug='${{inputs.debug}}'
        echo "${debug}"
        if [[ "${debug}" == "true" ]]; then
          echo "[🐙] Enabling debug logging."
          set -x
        fi

        if [[ '${{inputs.command}}' == '' ]]; then
          echo "[🐙] Missing input: command"
          exit 1
        fi

        cat >./wolfi-act.apko.config.yaml <<EOL
        contents:
          repositories:
            - https://packages.wolfi.dev/os
          keyring:
            - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
          packages:
            - ca-certificates-bundle
            - wolfi-baselayout
            - busybox
            - bash
        EOL

        packages='${{inputs.packages}}'
        if [[ "${packages}" != "" ]]; then
          for package in $(echo "${packages}" | sed 's/,/\n/g'); do
            echo "    - ${package}" >> ./wolfi-act.apko.config.yaml
          done
        fi

        printf "[🐙] Building ephemeral container image from Wolfi packages... "
        if [[ "${debug}" == "true" ]]; then
          docker run --rm \
              -v ${PWD}:/work \
              -w /work \
              '${{ inputs.apko-image }}' \
              build \
              --arch=x86_64 \
              --sbom=false \
              wolfi-act.apko.config.yaml \
              wolfi-act:latest \
              wolfi-act.tar
        else
          echo "[🐙] Running debug"
          docker run --rm \
              -v ${PWD}:/work \
              -w /work \
              '${{ inputs.apko-image }}' \
              build \
              --arch=x86_64 \
              --sbom=false \
              wolfi-act.apko.config.yaml \
              wolfi-act:latest \
              wolfi-act.tar 2>/dev/null
        fi
        echo "done."

        printf "[🐙] Loading ephemeral container image into Docker... "
        if [[ "${debug}" == "true" ]]; then
          docker load < wolfi-act.tar
        else
          docker load < wolfi-act.tar >/dev/null
        fi
        echo "done."

        env > wolfi-act.github.env

        echo "[🐙] Running the following command in ephemeral container image:"
        echo '${{ inputs.command }}'
        echo "[🐙] Output:"
        if [[ "${debug}" == "true" ]]; then
          docker run -i --rm --platform linux/amd64 \
              -v ${PWD}:/work \
              -w /work \
              --env-file wolfi-act.github.env \
              wolfi-act:latest-amd64 \
              bash -exc '${{ inputs.command }}'
        else
          docker run -i --rm --platform linux/amd64 \
              -v ${PWD}:/work \
              -w /work \
              --env-file wolfi-act.github.env \
              wolfi-act:latest-amd64 \
              bash -ec '${{ inputs.command }}'
        fi
