# .github/workflows/grype-trivy-scan-example.yaml
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  wolfi-act:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wolfi-dev/wolfi-act@main
        with:
          packages: grype,trivy
          command: |
            set -x
            grype cgr.dev/chainguard/nginx
            trivy image cgr.dev/chainguard/nginx
