on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jdolitsky/wolfi-act@main
      with:
        packages: grype,crane
        command: |
          set -x
          for img in "cgr.dev/chainguard/nginx" "cgr.dev/chainguard/wolfi-base"; do
            grype "${img}"
            crane manifest "${img}"
          done
          grype cgr.dev/chainguard/nginx
          echo "---"
          grype cgr.dev/chainguard/wolfi-base
          echo "---"
          whoami
