on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jdolitsky/wolfi-act@main
      with:
        packages: grype
        command: |
          grype cgr.dev/chainguard/nginx
          echo "---"
          grype cgr.dev/chainguard/wolfi-base
          echo "---"
          whoami
    - uses: jdolitsky/wolfi-act@main
      with:
        packages: crane
        command: |
          set -x
          crane manifest cgr.dev/chainguard/nginx
          crane manifest cgr.dev/chainguard/wolfi-base
